<?php 

# Navigations-Leiste oben


# Spracheinstellungen
  $language = '';
  $lang['de'] = '0';
  $lang['en'] = '0';
  $lang['fr'] = '0';
  $lang['ru'] = '0';
  $lang['cs'] = '0';
  $lang['pl'] = '0';
  $lang['es'] = '0';
  $lang['hu'] = '0';

  $charset = 'utf-8';

# Men&uuml;-Leiste



# Autor

# Seitenkopf

# Seitenfu&szlig;


# Verlinkungen

# Weitere Einstellungen
  $css_in = '@imort url(css/style.css);';
  $javascript = array("jquery-ui", "js/ajax.js", "jquery");

  #### NICHT Ändern:
  $basedir = dirname(__FILE__);
  require_once('tuc4.inc');
?>
