<?php 

# Navigations-Leiste oben
  $nav['Professur Datenverwaltungssysteme'] = 'https://www.tu-chemnitz.de/informatik/DVS/';
  $nav['Studienleistungen'] = 'https://www-user.tu-chemnitz.de/~malth/index.html';


# Spracheinstellungen
  $language = '';
  $lang['de'] = '0';
  $lang['en'] = '0';
  $lang['fr'] = '0';
  $lang['ru'] = '0';
  $lang['cs'] = '0';
  $lang['pl'] = '0';
  $lang['es'] = '0';
  $lang['hu'] = '0';

  $charset = 'utf-8';

# Men&uuml;-Leiste



# Autor
  $autor = 'Malte Thormählen';
  $email = 'malthor@mailbox.org';

# Seitenkopf

# Seitenfu&szlig;


# Verlinkungen

# Weitere Einstellungen
  $javascript = array("jquery-ui");

  #### NICHT Ändern:
  $basedir = dirname(__FILE__);
  require_once('tuc4.inc');
?>
